### ISSUE TITLE
[BUG] Unable to add frontmatter to note

### ISSUE THREAD

**Issue by Quorafind** [RafaelGB/obsidian-bd-folder#10]
**Describe the bug**
A clear and concise description of what the bug is:

Input things in cell didn't send to the original note's frontmatter

**To Reproduce**
1. Add a new column.
2. Change the name of column
3. Input anything in the cell of the column

**Expected behavior**
After add new column, I can input things in the cell.

**Screenshots**

![image](https://user-images.githubusercontent.com/13215013/164976391-dec7dffd-868b-4b82-bade-321550e95a10.png)

**Desktop (please complete the following information):**
```
SYSTEM INFO:
	Obsidian version: v0.14.6
	Installer version: v0.13.31
	Operating system: Windows 10 Pro for Workstations 10.0.19043
	Login status: logged in
	Catalyst license: vip
	Insider build toggle: on
	Live preview: on
	Legacy editor: off
	Base theme: light
	Community theme: Minimal
	Snippets enabled: 11
	Safe mode: off
	Plugins installed: 91
	Plugins enabled: 78
		1: Workbench
		2: Hotkeys for starred files and searches
		3: Tag Wrangler
		4: Remember cursor position
		5: Text expand
		6: Hotkeys for templates
		7: Privacy Glasses
		8: Maximise Active Pane
		9: QuickAdd
		10: MetaEdit
		11: Pandoc Plugin
		12: Hotkey Helper
		13: Hotkeys for specific files
		14: Longform
		15: Templater
		16: Calendar (Beta)
		17: Quick Explorer
		18: Readwise Official
		19: Customizable Sidebar
		20: Folder Note Core
		21: Pane Relief
		22: Tag Page Preview
		23: URI Commands
		24: Excalidraw
		25: Admonition
		26: Style Settings
		27: Obsidian42 - BRAT
		28: Customizable Menu
		29: AidenLx's Folder Note
		30: Copy Block Link
		31: Kanban
		32: Icon Shortcodes
		33: Dictionary
		34: Task Changer
		35: Link Favicons
		36: Icon Folder
		37: Hider
		38: Sortable
		39: Bartender
		40: Outliner
		41: Global Hotkeys
		42: Minimal Theme Settings
		43: Better Command Palette
		44: Supercharged Links
		45: Second Window
		46: Settings Search
		47: Various Complements
		48: Dynamic Highlights
		49: Customizable Page Header and Title Bar
		50: Local REST API
		51: RSS Reader
		52: Diagrams
		53: Dialogue
		54: AidenLx's Folder Note - folderv component
		55: Query Control
		56: Lapel
		57: Zoom
		58: Search on Internet
		59: Creases
		60: Auto Link Title
		61: Footnote Shortcut
		62: Jump to link
		63: Obsidian Charts
		64: Sliding Panes (Andy's Mode)
		65: Spaced Repetition
		66: Incremental Writing
		67: Natural Language Dates
		68: Snippetor
		69: Zotero Plugin
		70: Custom Frames
		71: Version History Diff
		72: Breadcrumbs
		73: Banners
		74: Obsidian Memos
		75: Hover Editor
		76: Omnisearch
		77: Dataview
		78: DB Folder

RECOMMENDATIONS:
	Custom theme: for cosmetic issues, please first try updating your theme to latest. If still not fixed, please try to make the issue happen in the help vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the help vault or disable community plugins.
```

**Additional context**
No.

**Comment by RafaelGB** [comment]
@Quorafind Thanks for your report. I have found the problem and I am working on it, I will deploy new version as hotfix

**Comment by RafaelGB** [comment]
hot fix released on 0.0.6.

There was a race condition + column key not updated, so rows was trying to change old key values

waiting confirm to close this issue

**Comment by Quorafind** [comment]
Now I added a new column and it works ~~~. 

But consider UX: 

Is there any way to show users that they had added a column didn't exist?
Or just remove the column that didn't exist? 
Or add frontmatter to note when people input anything to cell of the column?

Maybe I need to add a need fr issue for this.

**Comment by RafaelGB** [comment]
If you add a new column, this will add the new field into all rows. Same when you delete it, it will remove the field from all rows where it exist.

The last one is a good improve, add the field in case of didnt exist yet :)

In my backlog, as knowed bug, I notice that if you add a column and in some row the column already exist, duplicate the field.

I will try to fix it. Thanks for you ideas 😄😄
