### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'remove')

### ISSUE THREAD

**Issue by zubayrrr** [RafaelGB/obsidian-bd-folder#13]
`TypeError: Cannot read properties of null (reading 'remove')` is thrown as soon as obsidian is opened with the plugin installed. Whenever I try to open a file it throws the same error and the file is unable to open.

If I disable the plugin, reload and navigate to a different file and then restart obsidian, enable the plugin back and restart; the plugin doesn't not throw the error but if I navigate to a different file and then try to open the DB file it starts throwing the error again.
Note: I have tested this in a newly created obsidian vault with only dataview plugin installed and I didn't face these errors.

1. Go to 'Download the latest files from releases'
2. Click on 'Reload Obsidian using F5 or restart'
3. `Ctrl + Shift + I` to open console for the error.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.4 LTS x86_64 
 - Browser: Brave
 - Obsidian Version: 0.14.6 (Flatpak)

**Comment by RafaelGB** [comment]
With dataview enabled the problem does not persist, right? I will try to reproduce it as soon as posible. Looks like it needs a plugin dependency inside the manifest with dataview

**Comment by zubayrrr** [comment]
I just checked it with `0.14.6 AppImage` and I am no longer facing this issue. 
But as for your question...I did face it even with dataview enabled. I thought it might be that dataview needs to be initialized before bd-folder can do anything. I am not sure what the problem is.

**Comment by RafaelGB** [comment]
Confirmed. tomorrow I will develop inside onload plugin method a check if data view is available thanks for your testing =)

Its the search engine behind

**Comment by RafaelGB** [comment]
0.0.7 is up! 
I am waiting a confirmation to close this issue

**Comment by zubayrrr** [comment]
Hey, I got a chance to test the latest version. To confirm, I am not facing this error but I might have spotted a new issue(creating a new issue so you can close this one)
