### ISSUE TITLE
Still can’t install via BRAT

### ISSUE THREAD

**Issue by DitchComfort** [RafaelGB/obsidian-bd-folder#14]
I still have problems installing via BRAT?

![7EABB6D3-2C2D-42BE-B105-0C87BB4A8E7D](https://user-images.githubusercontent.com/77794110/165197536-4dfb9b89-49bf-4495-a405-9774ed02691c.jpeg)

**Comment by RafaelGB** [comment]
I could no reproduce the issue. Can install/unsinstall with BRAT without problems

**Comment by DitchComfort** [comment]
Sorry, I can also install/unsinstall with BRAT. I don't know what was wrong yesterday.

**Comment by RafaelGB** [comment]
Do not worry. It looks like a punctual connection problem

**Comment by RafaelGB** [comment]
do not worry. It looks like a punctual connection problem

Un saludo
________________________________
