### ISSUE TITLE
newly created file getting moved to a dir view_state creates

### ISSUE THREAD

**Issue by zubayrrr** [RafaelGB/obsidian-bd-folder#16]
This is what my folder structure looks like:
![image](https://user-images.githubusercontent.com/31969517/165866302-3706713b-3272-48ef-b4f3-2a26debfe2dc.png)

I have a test db folder under which I created a file `test db`

![image](https://user-images.githubusercontent.com/31969517/165866347-01a09dfd-27cc-4eb3-987e-09fd1dc68eb0.png)

Is it supposed to create a new dir `check` which is the `view_state` value and it moved the file `new file` to `check` dir; which should be under `test db` dir. Is this a bug?

**Comment by RafaelGB** [comment]
this is a config feature of v0.0.7

Check the release note:

### Shiny new things
- New local property `group_folder_column` to specify a select column type column. This column will be used to group the notes into subfolders with the same cell value. The subfolder will be created if it does not exist. [ISSUE#11](https://github.com/RafaelGB/obsidian-bd-folder/issues/11)

If you don't want to use it, you can modify it changing the local database config
1. 
<img width="188" alt="Screenshot 2022-04-29 at 08 24 19" src="https://user-images.githubusercontent.com/11924043/165894437-e6253c22-cce2-4253-9a2e-998467eb1267.png">

2. 
<img width="506" alt="Screenshot 2022-04-29 at 08 24 40" src="https://user-images.githubusercontent.com/11924043/165894471-6560b01e-1aaf-4b5e-a610-0c99607b94ec.png">

**Comment by RafaelGB** [comment]
Spoiler alert with 0.0.8 =)

<img width="138" alt="Screenshot 2022-04-29 at 10 15 38" src="https://user-images.githubusercontent.com/11924043/165908355-c53e7e5c-0f3c-42e4-9772-e911b984055f.png">

**Comment by SpocWeb** [comment]
Hi, first of all thank you very much for providing this PlugIn!!
I don't quite understand how the "Columns to group by" Feature should work though. 
I have a Database Folder with Country*.md Files and each Country has a Continent-ID Inline Field. 

- First of all the  "Columns to group by" Input Field has a Search Icon, but does not search. Instead I try to type in the Field Name I would like to group by: Continent-ID 
But then the Table is just emptied and no more records show

- Secondly I would like the individual Files to be moved into the corresponding Continent-ID Subfolders and to this purpose I tried the Slider "Group all Files into Folders automatically", but nothing happened. 

Please provide a small documentation how to use this Feature in your GitHub documentation. 
Alternatively explain it to me and I can create a Pull Request to update the Documentation. 
thank you very much...
