### ISSUE TITLE
Bug when trying to install trough Obsidian BRAT

### ISSUE THREAD

**Issue by isle99** [RafaelGB/obsidian-bd-folder#3]
"The release is not complete and cannot be downloaded. main.js is missing from the release.

**Comment by RafaelGB** [comment]
V0.0.1 was pre-release and is the unique without the correct dist

Last one has the correct main.js and others.
<img width="1225" alt="Screenshot 2022-04-20 at 22 04 08" src="https://user-images.githubusercontent.com/11924043/164313857-ecdc41b6-c753-46ad-9082-bc2a106513d8.png">
