### ISSUE TITLE
[Fearure request] Convert mov to gif in the readme

### ISSUE THREAD

**Issue by danieltomasz** [RafaelGB/obsidian-bd-folder#6]
COnverting mov to giv will make them accessible  in the readme page
[Convert Movie(.mov) file to Gif(.gif) file in one command line in Mac Terminal](https://gist.github.com/SheldonWangRJT/8d3f44a35c8d1386a396b9b49b43c385)

should also work on other operating systems

**Comment by RafaelGB** [comment]
I used an online converter. cherry picked to master. With futures releases I will try to find another way to show de documentation.

Thanks for your comment!

**Comment by danieltomasz** [comment]
If you  ever need it  in the future (and have any unix-like system with terminal), this is one liner converting all  mov files
```
find ./ -name "*.mov" -exec sh -c  'ffmpeg -i "$1" -pix_fmt rgb8 -r 10 "$(basename "$1" .mov).gif" && gifsicle -O3 "$(basename "$1" mov).gif" -o "$(basename "$1" mov).gif"' _ {} \;
```

**Comment by RafaelGB** [comment]
saved on my bash snippets
