### ISSUE TITLE
[BUG] Style Css casued theme's problem

### ISSUE THREAD

**Issue by Quorafind** [RafaelGB/obsidian-bd-folder#7]
![image](https://user-images.githubusercontent.com/13215013/164874229-195ebd54-1107-43b0-9e30-98af7157e75c.png)

Seems like some css selector will influence all the Obsidian

**Comment by RafaelGB** [comment]
thanks for the report.

I will try to fix it in future versions with custom prefix

**Comment by zubayrrr** [comment]
I would like to contribute to this, specifically, I want to use the CSS variables instead of the hardcoded hex values. @RafaelGB If you're not already working on this, I'd be happy to make a PR :)

**Comment by RafaelGB** [comment]
All help is welcome! I will work on it when I finish my actual branch of Drag and drop columns.

Actually exist a function in ‘helpers/styleHelpers.ts’ to add in those hardcoded values if you want to use it

Un saludo
________________________________

**Comment by zubayrrr** [comment]
@RafaelGB Hey, correct me if I am wrong but I thought I only needed to change values in `/styles.css` from hardcoded to `var(--var-name)` (from the existing obsidian variables)

**Comment by RafaelGB** [comment]
css its not my strength. I think it need to be changed in both sides. The hardcored tags inside code and the .css with —var

Un saludo
________________________________

**Comment by RafaelGB** [comment]
your contribution along with the dnd columns functionality is now available in version 0.0.5!

Added in readme.md & changelog.md

This Issue is closed. Thank you very much
